x-backend-service: &x-backend-service
  build: .
  env_file:
    - .env
  restart: unless-stopped

services:

  migrate:
    <<: *x-backend-service
    depends_on:
      - postgres
    command: python manage.py migrate --noinput
    restart: "no"

  backend:
    <<: *x-backend-service
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: [ "gunicorn", "-c", "/app/app/gunicorn.py", "app.wsgi" ]

  bot:
    <<: *x-backend-service
    expose:
      - 8080
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: python manage.py run_bot

  celery-worker:
    <<: *x-backend-service
    depends_on:
      - bot
      - postgres
      - redis
    command: celery -A app worker --loglevel=info

  celery-beat:
    <<: *x-backend-service
    depends_on:
      - celery-worker
    command: celery -A app beat --loglevel=info

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8000:80"
    volumes:
      - static_volume:/static
      - ./nginx/static/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - bot

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres  # Need a better password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    command: redis-server
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  postgres_data:
  static_volume:
