# Generated by Django 5.0.12 on 2025-02-24 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sending',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('topic_id', models.BigIntegerField(default=None, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userbot.message')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
    ]
